stages:
  process:
    cmd: python src/process.py
    deps:
    - data/penguins.csv
    - src/process.py
    params:
    - process.random_state
    - process.train_size
    outs:
    - data/processed/penguins_test.csv
    - data/processed/penguins_train.csv
  featurize:
    cmd: python src/create_features.py
    deps:
    - data/processed/penguins_test.csv
    - data/processed/penguins_train.csv
    - src/create_features.py
    outs:
    - artifacts/feature_encoder.joblib
    - artifacts/label_encoder.joblib
    - data/processed/test_processed.csv
    - data/processed/train_processed.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/test_processed.csv
    - data/processed/train_processed.csv
    - src/train.py
    params:
    - train.n_neighbors
    - train.test_dataset_name
    - train.train_dataset_name
    outs:
    - artifacts/model.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - artifacts/model.joblib
    - data/processed/test_processed.csv
    - src/evaluate.py
    params:
    - evaluate.test_dataset_name
    outs:
    - eval
metrics:
- eval/metrics.json
plots:
- eval/plots/metrics:
    x: step
- eval/plots/images
- eval/plots/sklearn/DVC confusion matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- eval/plots/sklearn/DVC ROC curve.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
- eval/plots/custom/feature importance.json:
    template: bar_horizontal
    x: feature_importance
    y: feature_names
